kind: Task
apiVersion: api.ipicture.vip/v1alpha1
metadata:
  name: my-task
spec:
  steps:
    - name: step1
      image: busybox:1.28
      command: ["sh"]
      args: ["-c", "echo step1"]
    - name: step2
      image: busybox:1.28
      command: [ "sh" ]
      args: [ "-c", "echo step2" ]