apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tasks.api.ipicture.vip
  labels:
    version: "0.1"
spec:
  group: api.ipicture.vip
  names:
    kind: Task
    plural: tasks
    singular: task
    listKind: TaskList
    shortNames:
      - ta
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}